# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define "master" do |containerhost01|

    containerhost01.vm.box = "ubuntu/bionic64"
    containerhost01.vm.network "forwarded_port", guest: 9000, host: 9001
      #containerhost01.vm.network "public_network", bridge: "ens3"
      containerhost01.vm.network "private_network", ip: "192.168.50.2"
    containerhost01.vm.hostname = "master"
      containerhost01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.name = "master"
      end
    containerhost01.vm.provision "shell" do |s|
      s.inline = "sudo apt update"
      s.inline = "sudo apt -y upgrade"
      s.inline = "git clone https://github.com/lucaspsacchi/Trab1-TAAD.git"
      s.inline = "apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common"
      s.inline = "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      s.inline = "apt-key fingerprint 0EBFCD88"
      s.inline = "add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable""
      s.inline = "apt update"
      s.inline = "apt -y install docker-ce docker-ce-cli containerd.io"
      s.inline = "systemctl start docker"
      s.inline = "systemctl enable docker"
    end
  end
  config.vm.define "worker" do |containerhost02|

    containerhost02.vm.box = "ubuntu/bionic64"
      #containerhost02.vm.network "public_network"
      containerhost02.vm.network "private_network", ip: "192.168.50.3"
    containerhost02.vm.hostname = "worker"
      containerhost02.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.name = "worker"
      end
    containerhost02.vm.provision "shell" do |s|
      s.inline = "sudo apt update"
      s.inline = "sudo apt -y upgrade"
      s.inline = "git clone https://github.com/lucaspsacchi/Trab1-TAAD.git"
      s.inline = "apt -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common"
      s.inline = "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      s.inline = "apt-key fingerprint 0EBFCD88"
      s.inline = "add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable""
      s.inline = "apt update"
      s.inline = "apt -y install docker-ce docker-ce-cli containerd.io"
      s.inline = "systemctl start docker"
      s.inline = "systemctl enable docker"
    end
  end
end
